### ISSUE TITLE
TagProperty should be Sized

### ISSUE THREAD

**Issue by masihyeganeh** [kellerkindt/asn1rs#17]
Hi. I had time today to take another look at this, but I couldn't get it compiled. because of this:
https://github.com/kellerkindt/asn1rs/blob/6c3c93a34e8e3bb06ff9b69cf0e0b16c506d3b01/asn1rs-model/src/model/mod.rs#L1062

I believe it should be:
``` rust
pub trait TagProperty: Sized {
```

At least with rust v1.46.0

**Comment by kellerkindt** [comment]
Hi, thanks for the heads-up. I am currently heavily refactoring the Tag behaviour locally but haven't had time to finalize and commit it yet.

**Comment by kellerkindt** [comment]
After merging #19 this should no longer be an issue. Feel free to open a new issue if the issue still persists
