### ISSUE TITLE
Build failure in model: `syn::Item` cannot be formatted using `{:?}`

### ISSUE THREAD

**Issue by badicsalex** [kellerkindt/asn1rs#76]
With both the crates.io version and on master, I get the following build error:

```
error[E0277]: `syn::Item` doesn't implement `std::fmt::Debug`
   --> /home/alex/.cargo/git/checkouts/asn1rs-f6cc173094da5683/b189ef6/asn1rs-model/src/ast/mod.rs:117:40
    |
117 |         println!("Matching item {:?}", item);
    |                                        ^^^^ `syn::Item` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
    |
    = help: the trait `std::fmt::Debug` is not implemented for `syn::Item`
    = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I guess the problem is that `if cfg!` is a runtime gate, and the gated code still has to build. And maybe the fact that the build now uses `syn v1.0.109`. The `Debug` trait for `syn`'s `Item` can be enabled with the `extra-traits` feature flag. 

(P.S.: Great work with the decoder, I'm also using it to decode v1.4.1 CAMs :) It works well once I get it to build.)

**Comment by kellerkindt** [comment]
Hi there, in which configuration do you use asn1rs? I can't get it to fail.

```
cargo build -p asn1rs --features debug-proc-macro
...
   Compiling syn v1.0.109
   Compiling syn v2.0.13
...
    Finished dev [unoptimized + debuginfo] target(s) in 21.33s
```

**Comment by kellerkindt** [comment]
Interesting ... why does the CI not fail? ... Hopefully fixed in 756fb55 ?

**Comment by kellerkindt** [comment]
Thanks for reporting, anyway!

**Comment by kellerkindt** [comment]
Could you please confirm that this is fixed now?

**Comment by badicsalex** [comment]
Yup, it works now. Thanks for the speedy response.
